# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20160720_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default=None, max_length=20, verbose_name='пол'),
        ),
    ]
