# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160720_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.City', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='день рождения'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Faculty', verbose_name='факультет'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], default=None, max_length=20, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='номер телефона'),
        ),
    ]
