# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160720_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Картинка'),
        ),
    ]
