# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160721_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, default=None, upload_to='images', verbose_name='Картинка')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name_plural': 'Статьи | История',
                'verbose_name': 'Статья | История',
                'ordering': ['-pub_date'],
            },
        ),
    ]
